Current year leaderboard
joaofogoncalves/aim4 pull request #3
Opened 2022-01-05 18:32 UTC by cauenapier

2022-01-05 19:07 UTC, joaofogoncalves requested changes
I Don't think we need an extra tab, just another column on same list, and the possibility to order it.
https://mdbootstrap.com/docs/b4/jquery/tables/sort/

2022-01-05 19:07 UTC, joaofogoncalves commented on aim4/challenges/views.py
> +import datetime
Unecessary import

2022-01-06 17:37 UTC, cauenapier commented
Just out of curiosity, @joaofogoncalves 
I was divided between writing the total distances as a property or making it a database attribute. How would you decide between the two options?

My rationale was: if pages loads are more often then new entries (new activities), then it is better to add this as a database attribute, since we will just calculate the new total distance when a new activity is added.
On the other hand, if page loads (which is the case now) is less often then new entries, it might be better to leave the calculation of the total distance whenever we open up the page.

Is this line of thought correct? Is there something else that should be taken into consideration?

2022-01-06 18:21 UTC, joaofogoncalves commented
That is the correct thinking, but in such low loads as we have right now, not very important.

2022-01-06 18:23 UTC, merged